trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: scripts
  displayName: 'repetitive tasks'
  jobs:
  - job: scripts
    displayName: 'evicted pods cleanup'
    steps:
      - task: Bash@3
        inputs:
          targetType: 'filePath'
          filePath: "$(System.DefaultWorkingDirectory)/clean.sh"


